name: Deploy para o azure

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@main

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: "7.0"
            
            - name: Build with dotnet
              run: dotnet build --configuration Release
            
            - name: dotnet publish
              run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/seboonline
            
            - name: Azure Login
              uses: azure/login@v1.1
              with:
                creds: ${{ secrets.AZURE_DEPLOY }}
              
            - name: Deploy to Azure Web Apps
              uses: azure/webapps-deplot@v1
              with:
                app-name: "seboonline"
                slot-name: "production"
                package: ${{env.DOTNET_ROOT}}/seboonline